# head
menu:
  Home: /
  Archives: /archives
rss: /atom.xml
favicon: /favicon.png

# main
date_format: 'MMMM D, YYYY'
excerpt_link: READ MORE
comment_link: 0 COMMENTS

# foot
# themes_mata: ' ❤ '
google_analytics: